//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alquiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alquiler()
        {
            this.pago = new HashSet<pago>();
        }
    
        public int idAlquiler { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public int IdInquilino { get; set; }
        public int IdInmueble { get; set; }
        public Nullable<int> borrado { get; set; }
    
        public virtual inmueble inmueble { get; set; }
        public virtual inquilino inquilino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pago> pago { get; set; }
    }
}
