//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inmueble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inmueble()
        {
            this.alquiler = new HashSet<alquiler>();
        }
    
        public int idInmueble { get; set; }
        public string direccion { get; set; }
        public int ambientes { get; set; }
        public string tipo { get; set; }
        public string uso { get; set; }
        public decimal precio { get; set; }
        public int disponible { get; set; }
        public int idPropietario { get; set; }
        public Nullable<int> borrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alquiler> alquiler { get; set; }
        public virtual propietario propietario { get; set; }
    }
}
