//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaFramework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDInmobiliariaEntities1 : DbContext
    {
        public BDInmobiliariaEntities1()
            : base("name=BDInmobiliariaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alquiler> alquiler { get; set; }
        public virtual DbSet<inmueble> inmueble { get; set; }
        public virtual DbSet<inquilino> inquilino { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<propietario> propietario { get; set; }
    }
}
