//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int idPago { get; set; }
        public int nroPago { get; set; }
        public int idAlquiler { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal importe { get; set; }
        public int borrado { get; set; }
    
        public virtual alquiler alquiler { get; set; }
    }
}
